apiVersion: v1
kind: Service
metadata:
  name: medilab-dept-db-service
  #namespace: medilab-dept-db-ns
  labels:
    type: service
    env: dev
spec:
  type: ClusterIP
  ports:
    - port: 3306 
      targetPort: 3306
  selector:
    app: medilab-dept-db-pods
      
