apiVersion: v1
kind: Service
metadata:
  name: medilab-doct-service
  #namespace: medilab-app-ns
spec: 
 type: NodePort
 ports:
   - port: 9099
     targetPort: 9099
 selector:
   app: medilab-doct-service-pods